### ISSUE TITLE
mbile_device를 설정하면 오류가 발생합니다.

### ISSUE THREAD

**Issue by bagng** [stateofai/naver-paper#52]
ubuntu에서 account.json에 아래와 같이 설정하서 실행하면 오류가 발생합니다.
        "ua": "UA 1",
        "mobile_device": "iPhone SE"

 ua, mobile_device를 삭제하면 실행 잘 됩니다.

오류.
Traceback (most recent call last):
  File "/home/ubuntu/naver-paper/run_new.py", line 280, in <module>
    main(campaign_links, id, pw, ua, mobile_device, headless, newsave)
  File "/home/ubuntu/naver-paper/run_new.py", line 212, in main
    driver = add_options_mobile_device(driver, mobile_device)
  File "/home/ubuntu/naver-paper/run_new.py", line 160, in add_options_mobile_device
    new_driver = webdriver.Chrome(options=new_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: no chrome binary at /usr/bin/google-chrome

**Comment by bluesid** [comment]
@bagng 님 구동하는 환경이 어떻게 되실까요 ?
Mac 환경에서 python 3.9.13, 3.10, 3.11, 3.12 에서 이슈가 없고
oci ubuntu 환경에서 python 3.10.12 에서 문제 없이 실행이 됩니다.

에러 메세지로 보면 /usr/bin/ 하위에 google-chrome 가 없다는 것 같은데요.
Prerequisites 에 따라 크롬을 설치 하셨다면 해당 경로에 google-chrome 가 있어야 될듯 합니다.

**Comment by bagng** [comment]
@bluesid 제가 사용하는 환경은 oracle cloud입니다.(amd cpu)

↳ ls -al /usr/bin/google-chrome
lrwxrwxrwx 1 root root 31 Mar 26 13:19 /usr/bin/google-chrome -> /etc/alternatives/google-chrome

↳ uname -a
Linux monster-oracle-amd 6.5.0-1027-oracle #27~22.04.1-Ubuntu SMP Thu Jul 18 13:55:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

↳ lsb_release -a               
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

↳ python3                                          
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

mobile_device를 설정하지 않으면 실행 잘 됩니다.

**Comment by bluesid** [comment]
제가 실행하는 환경이랑 비슷하지만 AMD CPU 인게 다른 것 같긴 하네요.

**Comment by bluesid** [comment]
@bagng cpu 문제는 아닌걸로 했고 기존 옵션 복사하는 코드가 제대로 안되는 것 같아서 코드를 변경 했습니다.

**Comment by bagng** [comment]
@bluesid 제 생각에는 oracle cloud에서 실행하는게 다른 것 같습니다.
일단 저만 발생하는 것 같으니 close 하겠습니다.
수고하셨습니다.

**Comment by bluesid** [comment]
@bagng 추가되었던 기존 코드에서 기존 옵션 복사 부분이 제대로 동작하지 않아 headness 부분 잘 안되고 있어서 일단 수정은 해 뒀고요. 오류 메세지로 봤을 때도 amd cpu 문제는 아닌 거 같긴 해서 나중에 코드 merge되고 나면 확인 한번 해주시면 될듯 합니다.

**Comment by stateofai** [comment]
@bagng @bluesid 님, 두분께 collaborator 권한 드렸어요!
